### ISSUE TITLE
Add functionality to approve or reject pending suggestions

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#10]
This can be done via reactions (e.g. check to accept, cross to reject) and/or via commands `suggestion accept <ID>` and `suggestion reject <ID>`

Useful resource for awaiting reactions:
https://discordjs.guide/popular-topics/collectors.html#message-collectors

**Comment by marko-polo-cheno** [comment]
I'll keep it as text based for now
