### ISSUE TITLE
[EPIC] Resume support

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#129]
**Describe the problem.**
CSC gets many resumes to roast, often from first years. Currently, Codey does not have any features that helps with the roasting process. 

**Describe your proposed solution(s).**
We should integrate some functionality into Codey which somewhat "automates" the resume roasting process. From #270 we already have pdf->image conversion for resumes; the next step should be parsing resumes automatically through some sort of ATS (?) and give some sort of feedback.

**Comment by EdwinYi-JanYang** [comment]
https://replit.com/@EdwinYiJanYang/WebScraper#main.py

**Comment by mcpenguin** [comment]
Could we scrape WaterlooWorks? We can keep the jobs secret - it might be nice to just see the proportion of key words that show up for a given "line" of careers (eg Full Stack Dev)

**Comment by mcpenguin** [comment]
**Resume parser code that uses the Lever API: (resume-parser.vercel.app creator)**
https://github.com/KnlnKS/resume-parser

**Guides on how to build a resume parser:**
https://towardsdatascience.com/how-to-build-a-resume-parsing-tool-ae19c062e377
https://promptapi.com/blog/article/build-your-own-resume-parser-using-python-and-nlp
Second one looks really promising, Python might be the best language for this since it is more versatile and has more support for NLP/ML libraries

**Comment by mcpenguin** [comment]
I'm thinking of registering for Lever's API: https://www.lever.co/partnershipinterest/

There is also https://itsjafer.com/#/parser but I can't seem to make this work :/

**Comment by mcpenguin** [comment]
In lieu of Lever's resume parser, we could make our own? It seems like Lever made their API even stricter so the request is blocked by CORS once again, so we might want to consider making our own parser instead. The guide I linked last term uses Python, but there should be equivalent TS libraries as well.

@alexz429 @marko-polo-cheno What are your thoughts on this? I don't want to start any R&D unless you guys think this is a feasible idea.

**Comment by mcpenguin** [comment]
We could also subscribe to the free tier of this API from the same website:
https://apilayer.com/marketplace/description/resume_parser-api?utm_source=blog_apilayer&utm_medium=Referral&utm_campaign=blog_banner_apilayer
