### ISSUE TITLE
Create a resume guide for self checks

### ISSUE THREAD

**Issue by marko-polo-cheno** [uwcsc/codeybot#150]
Ask if they have 
- a header with github, linkedin, contact info
- a skills section
- an education section
- an exp section
- a projects section
- an optional distinctions/interests section
- buncha things about formatting, margins, font size, etc

Needs a lot more detail tbh

**Comment by mcpenguin** [comment]
We can ask upper years about good resume tips, and congregate the results. What do you think

**Comment by marko-polo-cheno** [comment]
> We can ask upper years about good resume tips, and congregate the results. What do you think

as the guy who did 95% of the past 20 resume critiques, I have a sufficient number of tips.
There's already a lot of resources written by UW ppl already.

The actual content isn't that important rn, but the way it is presented and flows to the user is important. hmm, how do you think this guide should be presented? A wall of bullet points is something I would not want to read haha

**Comment by mcpenguin** [comment]
I'm not sure personally, maybe we can just limit the bullet points to the important bits?
