### ISSUE TITLE
[FEATURE] Attach somebody's discord @ to ban messages for appeal channel

### ISSUE THREAD

**Issue by alexz429** [uwcsc/codeybot#185]
When somebody gets banned, they should need at least some form of way to communicate for appeals outside of exec email. No real functionality to log with codey has been done yet, but if they have one of the existing mods @ they can DM for appeals.

Would be nice to add this to config so its an easy change across years.

**Comment by smilesthesad** [comment]
By "somebody" should we have an array of available mods in the config? Or just have one individual

**Comment by alexz429** [comment]
Most likely one is sufficient, should just be an extra config var.
