### ISSUE TITLE
[FEATURE] sapphire .help

### ISSUE THREAD

**Issue by alexz429** [uwcsc/codeybot#186]
while commando had a pregenerated .help command, sapphire does not. Additionally, it seems providing descriptions of subcommands is either impossible or convoluted within code.

Potentially start making a .help README on the github, and setup a .help command that will DM users the link instead.

**Comment by mcpenguin** [comment]
With the new CodeyCommand and CodeyCommandDetails framework, this could possibly be automated by passing in an auto-generated `help` command for each command. For sub-commands, the instructions on how to use each command could be contained within an embed which is sent when `.main help` is called.

**Comment by mcpenguin** [comment]
The way Carl Bot does it currently is have a help command with `.help [command] [subcommand]`. The Sapphire client (which is passed into the business logic for all commands) should contain a registry of all the commands, so if our help command is similar to Carl Bot's, we should be able to get the description of the commands from said registry.

If not, we could make an external handler class (similar to what is done for RPS) that contains the detailed descriptions for each command, and incorporate the "setup" of that in `CodeyCommand`.

**Comment by mcpenguin** [comment]
Perhaps we could also set up some sort of helper script to autogenerate a markdown file with all the command descriptions as well.
