### ISSUE TITLE
Enable automatic branch deletion when PR is merged

### ISSUE THREAD

**Issue by Picowchew** [uwcsc/codeybot#211]
Instructions can be found [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches). I think in most cases, we would want the branch to be deleted after merging the PR. The deleted branch could always be restored if necessary though.

**Comment by alexz429** [comment]
done
