### ISSUE TITLE
User profiles to set roles

### ISSUE THREAD

**Issue by marko-polo-cheno** [uwcsc/codeybot#219]
**Describe the problem and the impact.**
Year roles are not sustainable or scalable unless automated. Why not promote user profiles and link profiles to roles?

**Describe your proposed solution(s).**
Update everyone's current role into user profile.
Set year roles for all years in user profiles.

**Comment by Alluq** [comment]
@marko-polo-cheno does this also address #12?

**Comment by marko-polo-cheno** [comment]
> @marko-polo-cheno does this also address #12?

Yes, imo this issue will be a solution that makes #12 an obsolete idea.

**Comment by Alluq** [comment]
This ticket will be broken into 2 smaller sub tasks

- [ ] #229 
- [ ] #230
