### ISSUE TITLE
[FEATURE] Member verification command

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#241]
With the Discord server supposed to function as an extension of the CSC office, and with the office now fully operational, we should implement some Codey commands that are office-related. One such command is a command that displays whether a specific quest id is a member.

The CSC website already has a similar functionality. We can either
- scrape from the members page of the CSC website, and query from there; or
- wait for the Web team to create an API with a JSON response for the members, and use that instead

The command should have
- a command that takes in a quest id and outputs a response (probably an embed) that displays if the user is a CSC member or not.
- we could also maybe show if they are a member for next term as well. I'm not sure how we would do this.
- if there are not a member, we should show them steps on how they can become a member and the perks of being one in the embed response.

**Comment by mcpenguin** [comment]
We can get the relevant user data from the CSC website, which should be covered by this issue:
https://git.csclub.uwaterloo.ca/www/www-new/issues/472

**Comment by Picowchew** [comment]
The embeds should look something like the following.
![image](https://user-images.githubusercontent.com/58180935/184983752-f3eb1ee3-26e9-41b6-90d9-ff8fd4992968.png)
![image](https://user-images.githubusercontent.com/58180935/184983768-80fb8e4e-c635-4582-a3c2-82de4c03d1c5.png)
