### ISSUE TITLE
Disable command not found message

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#27]
Any messages starting with a . would trigger a command not found message, this can get annoying. We should find a way to disable this.

**Comment by kallentu** [comment]
Is this still relevant?
https://github.com/discordjs/Commando-guide/blob/master/removing-the-unknown-command-response.md

**Comment by gzcharleszhang** [comment]
@kallentu yeah that’s prob how u do it haha, you wanna work on this issue?
