### ISSUE TITLE
Slashify Interviewer

### ISSUE THREAD

**Issue by hydrobeam** [uwcsc/codeybot#283]
**Describe the problem and the impact.**
_Is there an issue you want to solve? Who does this feature impact? How many people will this feature impact? Will this feature be used often? What will happen if we *don't* implement this feature? Please clearly and concisely describe the problem you are facing._

There are lots of interviewer commands that aren't slashified

**Describe your proposed solution(s).**
_Please provide us with as much detail as possible and feel free to suggest more than one solution if there are alternative solutions. We may follow back up to clarify details we aren't sure of._
Slashify them by replicating what was done for `coin`

**Deadlines**
_Do you want it done by a certain date? Describe how urgently you need the feature complete. Please be specific and provide additional context if needed. This will help us with prioritization._
Probably by next week

**Additional Information**
_Feel free to add screenshots or any other contextual information we should know for building this feature._
I'm down to work on this

**Comment by hydrobeam** [comment]
Oh, didn't realize #277 was up 😅

**Comment by mcpenguin** [comment]
If you want to work on this, assign yourself to the issue and connect your branch to the issue :)) I used "revamping" in #277  because I wanted to brainstorm some new features we could add, and slashifying interviews would make that easier.

**Comment by hydrobeam** [comment]
I don't have the perms to assign to an issue 😳, could that be done?
