### ISSUE TITLE
meta: Rename primary branch to `main` from `master`

### ISSUE THREAD

**Issue by hydrobeam** [uwcsc/codeybot#292]
Not really relevant to the codebase, moreso about git.

`main` is the default branch name in `github` and `gitlab` and it'd be a little more convenient if codeybot matched the overall ecosystem + it's shorter. 

See the following link for more details + a HOWTO (it's pretty easy):
https://github.com/github/renaming

**Comment by mcpenguin** [comment]
`master` works fine imo - not too sure why we would want to rename it to `main` other than just for convention.

**Comment by hydrobeam** [comment]
well GH's original reasoning was that the `master` name is derived from the "master/slave" relationship, whereas `main` is a more neutral term.

Git itself is [considering](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) renaming the default branch name, citing the following reason:

> Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.  

Just feels like it's getting up to date with the times

**Comment by KevinBacabac** [comment]
It would also be quicker to type main and be more consistent with other repos. That'd help with onboarding new people by avoiding master vs main typos.

**Comment by Picowchew** [comment]
Done!
