### ISSUE TITLE
meta: Cleanup branches on remote

### ISSUE THREAD

**Issue by hydrobeam** [uwcsc/codeybot#293]
## Describe the problem and the impact.

Currently there are 29 branches on the repo, most of them being stale. After digging into it a bit it seems most of them are being used for development right on the remote branch. This adds a lot of clutter when trying to look for branches on the repo, or when fetching from remote and getting tons of dead/irrelevant branches. 

For instance, I use magit (a git front-end for emacs) and when trying to navigate around branches, there's a lot of extra stuff being pulled in from upstream which makes it more tedious. Image for reference (there are also duplicates of every branch since they're copied over when forking too).

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/70682032/184526082-47e3509d-97a2-4a3e-a307-79d12b040ed6.png">

Some of these are tags, which is totally fine, but having this many branches is a bit much.

## Describe your proposed solution(s).
 

- Do development on forks of the main repo as opposed to creating new branches remotely

The [github wiki here](https://github.com/uwcsc/codeybot/wiki/Onboarding:-First-Task) doesn't do a good job of explaining this process (doesn't at all :flushed:), but I'd be down to adapt this guide here from another project i've worked with:

https://docs.manim.community/en/stable/contributing/development.html

(it's really clean and thorough)

- Delete current stale branches and active branches when they've been merged into main

**Comment by mcpenguin** [comment]
For devs, I think it's okay if we let them do work on branches directly in the repository. I agree that we should delete the current stale branches though.

**Comment by hydrobeam** [comment]
> For devs, I think it's okay if we let them do work on branches directly in the repository

The reason why i suggested this is that if PR's are coming in pretty frequently then everytime a dev PR gets merged, their branch is gonna have to manually deleted from the repo. Or, if they're working on a feature that gets dropped or becomes redundant etc... Working off your own fork avoids this manual pruning problem (if somebody wants to fill up their own fork with branches they can go nuts) for free, since working off a fork is pretty much exactly the same as working off the main branch

**Comment by Picowchew** [comment]
Automatic branch deletion has recently been set up, as can be seen here, #211. I also agree that we should delete stale branches.

**Comment by Picowchew** [comment]
Unused branches are now deleted!
