### ISSUE TITLE
Show ties on coin leaderboard

### ISSUE THREAD

**Issue by Picowchew** [uwcsc/codeybot#301]
Currently, if 2 people have the same coin balance, then they will have different positions on the leaderboard. Instead, they should have the same position. For example, if the first 2 people each have 1000 coins, and the next person has 900 coins, then currently, the leaderboard shows positions 1, 2, and 3. However, the leaderboard should show positions 1, 1, and 3 instead.

**Comment by marko-polo-cheno** [comment]
I believe the best approach is to do this with SQL.
Be mindful of time tho. The more ordering, the slower the query!

https://www.sqlshack.com/overview-of-sql-rank-functions/

**Comment by probro27** [comment]
I have created a fork. Please assign me this issue :)
