### ISSUE TITLE
Make coin transfer subcommand

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#307]
## Description of proposed feature

Make a subcommand to transfer coins from your balance to another person's balance.

## How can the new feature be used?

`.coin transfer <username> <amt>` or `.coin t <username> <amt>`

(with the appropriate slash command versions)

**Comment by botatooo** [comment]
I can give a try at implementing this :D

**Comment by hydrobeam** [comment]
I think it shouldn't be one way and should also prompt the receiving person if they wish to accept the trade, just in case someone else doesn't wanna receive coins for any reason

**Comment by botatooo** [comment]
Ooh I could add a prompting option, opinions on that?

**Comment by Picowchew** [comment]
Yup, a prompt and confirmation from the other person sounds good!

**Comment by mcpenguin** [comment]
I agree with @hydrobeam - we should prompt the other user when transferring coins.

**Comment by botatooo** [comment]
How would this be implemented? Pinging the user in chat with some kind of reaction confirmation or dms?

**Comment by Picowchew** [comment]
I would prefer the former, since I think it would look nicer for the entire transfer to occur publicly.
