### ISSUE TITLE
Rewrite README with updated contributing guidelines

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#311]
## Description of proposed feature

The development process for Codey has changed, especially now that we have many outside contributors for the bot. We should document the process for contributing to standardize development and make it easier for new developers to contribute to the code.

**Comment by botatooo** [comment]
So a `CONTRIBUTING.md` that includes instructions on how to open a pr, make an issue, and a [code of conduct](https://contributor-covenant.org) if I understood correctly.

**Comment by mcpenguin** [comment]
I was thinking we can just have the contribute steps on the readme, but we could extract it out to another md file.

It would have how to set up your development environment and how to propose and work on issues. I didn't think of this initially but a code of conduct could be nice as well.
