### ISSUE TITLE
Make 1-player RPS for Codey

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#339]
## Description of proposed feature

Make Rock Paper Scissors (aka RPS) for Codey.

The first version of RPS we can make would be single-player. It would be very similar to blackjack: the player would say `.rps [bet amount]`, with the default bet amount being 10. We would then have an embed that shows up, similar to the one for blackjack, with three emoji buttons: Rock, Paper and Scissors. After the player selects a button, Codey would pick an option. If Codey wins, the bet is lost, and if the player wins, the bet is doubled, like in blackjack.

We can either use buttons or reactions for this. If we go for the former, we might want to instead wait for https://github.com/uwcsc/codeybot/pull/327 to be merged, since that adds support for components. 

## How can the new feature be used?

`.rps [bet amount]`

**Comment by marko-polo-cheno** [comment]
Need to figure out money tho. RPS might be preferable over black jack. Imo, ties make u lose 50% of the bet when against codey. For 2P, ties are just nothing happens.

**Comment by mcpenguin** [comment]
Single player embed example:
![image](https://user-images.githubusercontent.com/76544623/186747584-3a195d56-0158-4a00-b720-e5332eb3c2ea.png)
