### ISSUE TITLE
Unnecssary `Promise` returns and `async` functions

### ISSUE THREAD

**Issue by hydrobeam** [uwcsc/codeybot#346]
## Description of bug / unexpected behavior

While trying to cleanup some types in `src/codeyCommand.ts`, I noticed that `chatInputRun` and `messageRun` were both async. However, when inspecting the type definition in the parent class (`SapphireCommand`), I noticed that these methods were not `async` and were in fact also returning `Awaitable<unknown>` as opposed to the `Promise` buffet they currently do:

Sapphire: 
```js
messageRun?(message: Message, args: PreParseReturn, context: MessageCommand.RunContext): Awaitable<unknown>;
chatInputRun?(interaction: CommandInteraction, context: ChatInputCommand.RunContext): Awaitable<unknown>;
```

Codey
```js
  public async chatInputRun(
    interaction: SapphireCommand.ChatInputInteraction,
  ): Promise<APIMessage | Message<boolean> | undefined> {

  public async messageRun(
    message: Message,
    commandArgs: Args,
  ): Promise<Message<boolean> | undefined> {
```
This seems to impy that we're being overly specific/inaccurate here.

## Investigating
Looking into why these methods are `async`, there are two causes, for `chatInputRun`, `initialMessageFromBot` necessarily requires an `await` to get (so, the whole function must be `async`), but that's being removed by #329. Although for both methods, they call `commandDetails.executeCommand`, which returns a Promise that needs to be awaited.

This is odd because `CodeyCommandResponseType` (which #329 also removes due to redundancy) specifies that the return type is always a `string` or an `Embed`, and it's asyncness isn't being taken advantage of. Although, I noticed the return type of `executeCommand`  is a `Promise`, which shouldn't really be the case because it's always returning a string or a regular Embed object.

This also rings true for non slashy commands, which return things that can be awaited, but instead specify a return type of `Promise` where `await` would be more appropriate.

For instance: 
https://github.com/uwcsc/codeybot/blob/master/src/commands/profile/profile.ts#L67

## Proposed Solution

Types could also be adjusted manually, removing`Promise<>` returns from `executeCommand` definitions, and making unslashified commands use `awaitable`'s. There are a lot of these types being specified explicitly everywhere, so it might take a while.

Alternatively...

Disable the lint of `@typescript-eslint/explicit-module-boundary-types` which mandates specifying a return type for inherited methods. Then, turn the `commandDetail` into a class based deal, have `executeCommand` be a method (with the correct return type) and inherit types + delete existing types. This is a *little* much just to fix this issue, but it's got other benefits :flushed: I can expand my thoughts on the approach in a separate issue. 

## Additional comments

[`Types are fun`!](https://dwarffortresswiki.org/index.php/DF2014:Losing)

**Comment by mcpenguin** [comment]
Personally, I would rather have `messageRun` and `chatInputRun` return the current return type rather than (awaitable) `unknowns`, since the former is easier to debug (say if you return the wrong type). I'm also pretty sure `executeCommand` has to be `async`, since there are several instances where it fetches data from a database (eg coin) and so needs to be asynchronous. Not sure what benefits there are to Awaitables vs Promises - feel free to let me know the advantages; I can do some independent research myself.
