### ISSUE TITLE
Coin leaderboard shows names italicized

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#358]
## Description of bug / unexpected behavior

As above.

## Expected behavior

This shouldn't happen - all the names should be regular text.

## How to reproduce the issue
`/coin leaderboard` (on the main server) produces
![image](https://user-images.githubusercontent.com/76544623/187082269-a5564d8c-74e1-4065-8b24-ca543aea3a68.png)

## Additional comments

This is most likely caused by some usernames in the leaderboard having underscores, which Discord interprets as italic text.

**Comment by botatooo** [comment]
Can we escape these by surrounding the names by `quotes` or making them mentions (for future reference these don't ping the user)
