### ISSUE TITLE
Send reply in syscom channels if message contains substring of a syscom member ping

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#361]
## Description of proposed feature

(Feature request from @KevinBacabac)

If a message is sent in the channels #chat-with-syscom or #csc-irc and contains a substring of a syscom member ping (e.g. `r aymo`), send a reply to the user saying not to do that (since it doesn't actually ping them)

## Additional comments

Syscom users: raymo, merenber

**Comment by Picowchew** [comment]
This feature is not needed to be implemented.
