### ISSUE TITLE
Ping/DM particular users when office is open

### ISSUE THREAD

**Issue by SaurontheMighty** [uwcsc/codeybot#388]
## Description of proposed feature
Right now the office channel displays a checkmark or a cross to indicate the office status but if someone needs to visit this isn't that helpful. It would be great if Codey could DM/ping the user when the office becomes open.

## How can the new feature be used?
Implementation 1: A command: The user could send a command to Codey with an expiry date and Codey could DM/ping the user everytime the office is open until the expiry date.

Implementation 2: A role where the user could add the role if they want the ping and unenroll from the role when they no longer need it (after they successfully visited the office and got their thing done).

**Comment by Picowchew** [comment]
Let's have implementation 2.

**Comment by alexz429** [comment]
Imp 2 should have a very similar codeflow as coffeechat's current method to scan who is enrolled in coffee and dm them after. Maybe we can abstract this now that there is multiple use cases

**Comment by SaurontheMighty** [comment]
Where do we want Codey to ping the users with the role? 

I was thinking bot-spam or office-status.

#office-status might be good because its not really being used and anyone who doesn't like the messages can just mute that channel (they would still see the check/cross even if its muted).

**Comment by Picowchew** [comment]
I think DMs would look the cleanest, since a history of pings isn't needed to be maintained and ghost pings aren't nice. I agree that an abstraction would be good.
