### ISSUE TITLE
Blackjack spam if do not act within time limit

### ISSUE THREAD

**Issue by Picowchew** [uwcsc/codeybot#404]
## Description of bug / unexpected behavior

When playing blackjack and you do not act within the time limit, the bot keeps spamming `you didn't act within the time limit, please start another game!` until the bot gets restarted. Even when reacting to the original game, the bot removes the reaction and then the bot still continues to spam.

## Expected behavior

The bot should only send this message once.

## How to reproduce the issue

Start a blackjack game and do not act within the time limit.

## Additional media files

https://discord.com/channels/667823274201448469/762882537692332064/1033787340197466193

**Comment by jman005** [comment]
Fixed most likely by #481
