### ISSUE TITLE
Make insertion of new SQL table columns more dynamic

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#418]
## Description of bug / unexpected behavior

When reviewing https://github.com/uwcsc/codeybot/pull/416, which adds a new column to the user profile table, I realized that the current design of Codey is inflexible when handling new columns to existing tables. If the table (without the new columns) already exists, then the column would not be added (as the table already exists, and all we do is a `CREATE TABLE IF NOT EXISTS`). Similarly, if a column is deleted/renamed, this would not be reflected in any existing tables (without manual SQL queries).

## Expected behavior

We should implement some abstraction so that new columns can be added into existing tables without any manual SQL queries. This should be able to
- create the table if it does not exist
- not alter any existing columns in the original table that are also in the new table
- add any new columns that were not in the original table but are in the new table
- delete any columns that were in the original table but not in the new table

One method is to implement a helper that takes a list of column data and spits out an SQL query that adds any new columns to a table and deletes any columns that are not in it anymore, whilst keeping any existing ones intact.

**Comment by probro27** [comment]
I have an idea of how to implement this and since I worked on #416 I can integrate that code to work with this helper. 
So @mcpenguin  can you assign this to me :)

**Comment by probro27** [comment]
Hey @mcpenguin, let me know if I can take this up. Seems simple enough to implement :)
