### ISSUE TITLE
Explicit Codey User Friendly Errors

### ISSUE THREAD

**Issue by smilesthesad** [uwcsc/codeybot#424]
## Description of proposed feature
Previously, we used message.reply early if there were validation errors, e.g: "a user id must be provided". However with the migration to sapphire, we're doing `throw new Error` like so 
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/36215359/210125672-dc4468fd-66d1-4e04-84ab-a8de6c9e0704.png">

The issue with this is that we have a default message if we just throw a regular Error, instead of that message actually being sent to the user.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/36215359/210125541-2affc2d2-7797-492d-bdb5-8192f517fcfd.png">
We should develop a CodeyUserError, to make it very explicit when we're exiting early due to unintended use, which also makes debugging easier. Whenever we want to return an error message to the user, we can do something like `throw new CodeyUserError("a user id must be provided")` instead of message.reply. In the case we have unexpected errors that we do not want to display to a user, such as errors from API calls, throw new Error can still be used, and have the default message be displayed.

## How can the new feature be used?

Instead of message.reply when something goes wrong, we can throw an error while still giving the user an explanation of what went wrong. This makes it very clear from a regular message.reply to improve our codebase.

**Comment by Picowchew** [comment]
Currently, in some places in the codebase, strings are thrown. These can be changed into throwing the correct error type as well.
