### ISSUE TITLE
Fix images in README.md

### ISSUE THREAD

**Issue by Picowchew** [uwcsc/codeybot#430]
## Description of bug / unexpected behavior

The Codey images in README.md do not appear.

## Expected behavior

The images should appear.

## How to reproduce the issue

Take a look at the README.md file.

## Additional media files

![image](https://user-images.githubusercontent.com/58180935/213231692-ab5413b7-3f78-4a6b-9972-a99864e30a5d.png)

## Additional comments

Change the naming of the images to snake case from camel case.

**Comment by the-amazing-atharva** [comment]
Hey,

A beginner here. I cam across this issue while checking for labels

Have sent a PR fixing the issue.

Regards
