### ISSUE TITLE
Nuke messages with no attachments in #resume-critique

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#432]
## Description of proposed feature

#resume-critique should only contain messages with attachments (either pdfs or images). So, any messages without attachments should be removed, and Codey should DM the user with an explanation as to why their message was removed. Something like,

"Hey @username, we've removed your message from #resume-critique since only messages with pdfs or images are allowed to be posted there. If you would like to critique a resume, start a thread on the message containing the resume and write your feedback there!"

**Comment by probro27** [comment]
To support resumes sent in image form we can create a thread and just post that same image there as well.
