### ISSUE TITLE
Some pdfs don't get converted

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#440]
## Description of bug / unexpected behavior

A pdf was submitted in resumes, but was not converted to an image.

https://discord.com/channels/667823274201448469/1064978680960516237/1070552487796416562

## Expected behavior

This should not happen.

## How to reproduce the issue

Download the pdf in the message, send it in your own test channel and watch for output.

**Comment by jman005** [comment]
I can't seem to reproduce this even using the original resume, so this was most likely a one-off error, but I will keep this issue open for a little bit longer in case it appears again.

**Comment by probro27** [comment]
Closing for now until we see this issue arising again!
