### ISSUE TITLE
Blackjack games quit after one move and unable to start a new game if you win/lose upon start

### ISSUE THREAD

**Issue by NotMyLyfe** [uwcsc/codeybot#446]
## Description of bug / unexpected behavior
In a normal blackjack game, after doing one move, all reactions disappear as though you quit the game. You're unable to continue to play the current game and you're able to start a new game as though the current game is no longer in play.

When a game is won/lost upon start, there's about a one minute window where it states the game is still in play. Unable to start a game for approximately one minute where the previous game is considered "finished".

## Expected behavior
Reactions should persist until the game is lost by the user (if the current value the user has exceeds 21), the user decides to quit the game, or the user hits "Stand". User should also not be able to start a new game until the game is complete.

When a game is won/lost upon start, a user should be able to start a new game.

## How to reproduce the issue
Call the blackjack command with `.bj <value greater than or equal to 10>`.

If the game has not been won/lost upon start, press "H" to hit to proceed with the game. If the game is won/lost immediately after this, repeat the steps until it is possible for the player to have a second move. Attempt to perform a second move, as well as attempt to start a new game. An additional action should not be possible at this point and a second game can be made despite having a game in session.

If the game is won/lost upon start, attempt to start a new game immediately after. You will receive an error stating that there's a game in session despite already finishing one.

## Additional media files
<img width="958" alt="image" src="https://user-images.githubusercontent.com/30644833/217633277-4a315287-7b9a-4ccb-8e0e-5f406da8ac23.png">

**Comment by ethan-kwon** [comment]
Skill issue
