### ISSUE TITLE
Expand top 10 codey coin holders to top5/10/20

### ISSUE THREAD

**Issue by mcpenguin** [uwcsc/codeybot#462]
## Description of proposed feature

Currently, a cron job runs to assign the top 10 codey coin role to the top 10 codey coin holders in the server. We want to expand this to:
- assign a "top 5" role to the top 5 codey coin holders;
- similarly for "top 10"; and
- similarly for "top 20".

**Comment by Elfshot** [comment]
Should top x coin holders hold the roles for every top x group they're in or just the highest one?

**Comment by Fan-Yang-284** [comment]
I think just the highest one would be best.
