### ISSUE TITLE
Bots should not be able to have the Top 10 Coin Holder role

### ISSUE THREAD

**Issue by Picowchew** [uwcsc/codeybot#467]
## Description of bug / unexpected behavior

Currently, a bot is able to have the `Top 10 Coin Holder` role.

## Expected behavior

There should still be ten people with the `Top 10 Coin Holder` role, though they should all be non-bot users.

## How to reproduce the issue

Have a bot be in the top ten in terms of coins.

## Additional media files

![image](https://user-images.githubusercontent.com/58180935/226210759-38aeff7b-6d37-4ec7-a74f-2bb9a3aa53b7.png)

**Comment by Elfshot** [comment]
Resolved by #525 if merged
