### ISSUE TITLE
[EPIC] Create User Profiles

### ISSUE THREAD

**Issue by marko-polo-cheno** [uwcsc/codeybot#47]
User profiles are a nice way to get to know someone via a single .about command!

## Init
- [x] #139 

## Things to show in profile
- [x] #144
- [x] #145
- [x] #146
- [x] #142
- [x] #143
- [x] #147
- [x] #148
- [x] #141

## Display
- [x] #140

### How do we get user input
One command to edit/update each field

### Private or Public?
For now, all information within user profiles is public.

**Comment by gzcharleszhang** [comment]
Some things we should consider:
- What information should we include in the profile?
- How should we collect information? What commands?
- We can use this issue as the "parent" and keep track of smaller tasks that complete the user profiles feature.
