### ISSUE TITLE
Discord Bot Internship Repo Integration

### ISSUE THREAD

**Issue by EnamiYa** [uwcsc/codeybot#482]
## Description of the proposed feature
The proposed feature is a Discord bot that is linked to a dedicated channel for internships. The bot's purpose is to facilitate sharing job postings and adding them to the internship repo. It accomplishes this by parsing the shared links and scraping relevant internship-related information from the web page. The collected data can then be used to open a pull request using GitHub actions.

## How can the new feature be used?
1. A user shares a job posting link in the dedicated internship channel.
2. The bot reads the link and attempts to parse the information from the webpage. If the link is valid and contains sufficient information, the bot will automatically scrape the details. If the parsing is unsuccessful, the bot will prompt for manual input to ensure accuracy.
3. Once the information is gathered, the bot sends it back to the user for confirmation and allows them to edit or modify any of the scraped fields if necessary.
4. After the user confirms the information, the bot opens a pull request using GitHub actions.

The feature will: 
1. Facilitate the process of sharing job postings
2. Automate collecting the information from the job posting pages
3. Automate opening PRs

By implementing this feature, the Discord bot will help improve the internship repo by providing a seamless and efficient way to share job postings and keep the README file up to date.

**Comment by probro27** [comment]
Not to be worked on since the internship repository has been discontinued since 2024.
