### ISSUE TITLE
Threads not created automatically for resume reviews

### ISSUE THREAD

**Issue by Fan-Yang-284** [uwcsc/codeybot#496]
Links to error:
https://discord.com/channels/667823274201448469/1064978680960516237/1156367608275279902
https://discord.com/channels/667823274201448469/1064978680960516237/1156666410202841120
https://discord.com/channels/667823274201448469/1064978680960516237/1156734036241297469
... and the resumes after them.

Note that the threads for those resumes were kindly created by a server member.

**Comment by mcpenguin** [comment]
pdfs don't seem to be created automatically either.

Do we have an update on this?
