### ISSUE TITLE
Birthday Announcements for .profile

### ISSUE THREAD

**Issue by kallentu** [uwcsc/codeybot#50]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
For the `.profile`, have a section where people can put the date (month/day) of their birthday if they'd like and Codey will wish them a Happy Birthday in a public birthday channel or something. #off-topic or something?

**Additional context**
See `.profile` feature request elsewhere.

**Comment by smilesthesad** [comment]
In order to do this one we would have to support the day of the month first, which was decided against in the initial release as per the initial user profile ticket (Currently its more of a birth month). So unless we move forward with adding days, this is blocked for now :(.
