### ISSUE TITLE
Show Codey bot info - app version, repo link, issue templates

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#54]
- [ ] An `.info` command to show the current version of the app, link to the Github repo, and links to the issue templates
- [ ] Mention current app version and environment in the Codey startup message

We should show the current app/build version either via a command or during Codey startup message. This could be either the version tag for a production build, or the commit SHA tag for a staging build. These tags can be obtained from the docker image.

**Comment by mcpenguin** [comment]
I'll finish my work with slash commands first before doing this ticket :))
