### ISSUE TITLE
Backup database and logs

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#57]
Currently our production/staging database and logs live on a single GCP instance. This could be dangerous if the VM is deleted for any reason. We should investigate/explore ways to backup and store our data with minimal cost. Update this issue with your research findings.

A few questions we should address:
- Where do we store the data? (in a github repo, or in a cloud storage such as GCS or AWS s3)
- How often should we do a backup?
- How do we get the data from the GCP VM to its long-term storage destination?
- How much data can we store? How do we ensure we can keep backing up indefinitely?
- What are the costs associated with this long-term storage?
- How do we restore from backup? Do we have a script/tool to restore from the latest backup automatically?

**Comment by mcpenguin** [comment]
TODO: We need to research more and give more specific instructions for how to do this.

**Comment by alexz429** [comment]
https://geekflare.com/google-cloud-vm-backup/
in the "Automatically using Google Cloud Console" section, it described a very sound process to just snapshot the entire instance, keep however many snapshots we want, and restore from snapshot if the vm is ever deleted.
@mcpenguin @Picowchew thoughts?
