### ISSUE TITLE
Show areas of expertise when listing out interviewers

### ISSUE THREAD

**Issue by kallentu** [uwcsc/codeybot#58]
**Is your feature request related to a problem? Please describe.**
When you list out interviewers generally, you have no idea what they specialize in. I would like to see what areas they signed up to interview for.

**Describe the solution you'd like**
For all the lists of interviewers, show the interviewer areas of expertise on the side as well.

**Comment by marko-polo-cheno** [comment]
![image](https://user-images.githubusercontent.com/37851975/174411589-573c91e3-f2ad-43dd-87ac-d58df820c803.png)
