### ISSUE TITLE
Use GCP cloud logging driver for each codey container

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#75]
Currently, we have two types of logs:
1. Default docker container logs (stdout and stderr), which are saved inside `/var/lib/docker/containers/.../*-log.json`.
2. Command level logs using winston, which are saved in the `logs` directory for each codey deployment.

This poses a few problems:
- Hard to query logs, need to ssh into machine.
- Logs are not retained outside of the GCP instance.
- Logs are not structured.
- Logs are stored in two locations.

We should look into using the GCP log driver for our Codey containers, so we can use GCP cloud logging query viewer to see the logs inside GCP console.

**Comment by Alluq** [comment]
QQ, enabling cloud logging requires us to set up billing and everything, which might cost some money depending on how many logs we have, the first 50 gbs of logs are free but afterwards its 0.5 USD per GB. 
Are we going to reach that threshold? If so do we need to worry about funding for the codey bot?

**Comment by gzcharleszhang** [comment]
I don't think we will reach that threshold. We can enable cloud logging and monitor for usage for 1-2 weeks. Even if we go a little bit extra, we do have budget for the bot.

**Comment by Alluq** [comment]
you can now query for the logs of staging and production by adding this to the query text box in the log menu:
![image](https://user-images.githubusercontent.com/39013427/153137949-113d25ac-3c30-4f8a-a08d-95178178e557.png)
`jsonPayload.container.name: <name of codey instance here>`
for example with staging you can find all staging logs using:
`jsonPayload.container.name:/codey-staging`
