### ISSUE TITLE
Bootcamp Discord API errors in console

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#78]
There are consistent Discord API errors in console from the codey-bootcamp container. View the logs in GCP console for more details. We need to fix this before merging bootcamp features into master.

Example:
![image](https://user-images.githubusercontent.com/26018804/135361975-f9adb708-54aa-4e78-9b6a-163b6858f120.png)

**Comment by asdera** [comment]
the bugs are caused by the vc-0 text channels that aren't deleted right away (the cron tasks still tries to run logic on those channels)
