### ISSUE TITLE
[EPIC] Sapphire + Discord.js v13 Migration

### ISSUE THREAD

**Issue by gzcharleszhang** [uwcsc/codeybot#92]
## Summary
Discord.js v13 introduces support to new features such as slash commands and buttons. However, Commando is no longer supported in v13. Sapphire is the framework that is recommended by the discord.js team, hence we will be migrating to Sapphire incrementally.

## Notes
Commando -> discord.js 13 -> Sapphire is not possible because upgrading from discord.js 12 -> 13 breaks Commando.
Commando -> Sapphire -> discord.js 13 is not possible because upgrading to sapphire with djs 12 breaks Sapphire
Thus, we need to do a simultaneous update

## Phase 1: Commando -> Sapphire (within protected branch `sapphire_migration`)
1. Move all current functionality into the `oldCode` directory.
2. Incrementally "mirror" over features from Commando to Sapphire.
3. As commando and sapphire are effectively mutually incompatible, finish mirroring over all features before merging back into master
4. Take a look at the plugins, use whatever makes sense.
5. Reuse as much component code as possible, bulk of the work should be to revamp the command integration with the component features.

- [x] #158
- [x] #159
- [ ] #160
- [x] #161
- [x] #162
- [x] #163

### Resource
Sapphire: https://www.sapphirejs.dev/docs/Guide/getting-started/getting-started-with-sapphire
Subcommands plugin: https://www.sapphirejs.dev/docs/Documentation/api-plugins/modules/sapphire_plugin_subcommands
Logger (replace Winston): https://www.sapphirejs.dev/docs/Documentation/api-plugins/modules/sapphire_plugin_logger
Example using typescript with listeners, commands, preconditions, etc: 
https://github.com/sapphiredev/examples/tree/main/examples/with-typescript-recommended

## Phase 2: Use discord.js 13 functionality
1. Design a slash commands system within our app, or see if Sapphire has a framework for slash commands.
2. Incrementally mirror over feature from traditional command interface to slash commands, reuse as many components as possible.
3. Replace emote reactions with button.

**Comment by alexz429** [comment]
Sapphire FAQ:
Listeners represent non-message based updates from discordjs
They previously were the client.on type hooks, except also wrapped into component form.
check `ready.ts` for an example

Preconditions represent, well, preconditions, before a command is allowed to activate
this can take the form of permissions, channel states, etc
check the sapphire example linked above

all components, by default, activate based on their file name, so ping.ts will activate on "prefix + ping", and ready.ts will activate on the "ready" event. This can be changed by adding the optional "name" field, and additional hooks can be added with aliases, much like commando.
